### ISSUE TITLE
New Output(s) for the actionners

### ISSUE THREAD

**Issue by Issif** [falco-talon/falco-talon#282]
For the actionners creating an artifact, we should consider a way to export this artifact to somewhere. 

For example, a tcpdump put into an S3 bucket.

**Comment by sanchaysaxena** [comment]
HI @Issif , I am using Azure AKS, can we have a new output for azure environment, something like azure blob storage

**Comment by IgorEulalio** [comment]
Hey @sanchaysaxena thanks for your suggestion, I'll add this on the list of next steps, feel free to open a PR adding support for it meanwhile!!
